#ifndef GRAPHICS_CONF_H
#define GRAPHICS_CONF_H

#define DEFAULT_TILE_LEN 16
#define DEFAULT_SCREEN_TILES_Y 15
#define DEFAULT_SCREEN_TILES_X 20
#define MAX_LAYERS 2
#define MAX_SPRITES_PER_LAYER 5

#endif //GRAPHICS_CONF_H
